Fix build on aarm64
cabal build all on aarm64 fails to compile due to criterion-measurement-0.1.3.0 library 
"cbits/cycles.c:64:2: error: Unsupported OS/architechture/compiler!"

change to build only cardano-node and cardano-cli instead of build all, results in successful build.

Tested on FreeBSD 13.1 aarm64